In [1]:
import numpy as np
# import numpy

In [5]:
#create a 3*3 matrix
A = np.arange(21,30).reshape(3,3)
#print the matrix
print('\n\nMatrix A \n\n')
print(A)



Matrix A 


[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [3]:
# Transpose Matrix
print('\n\nTranspose of Matrix\n\n')
print(A.transpose())



Transpose of Matrix


[[21 24 27]
 [22 25 28]
 [23 26 29]]


In [9]:
# Matrix multiplication
B=np.arange(1,10).reshape(3,3)
C=np.arange(11,20).reshape(3,3)

#print the matrix
print('\n\nMatrix B\n\n')
print(B)

#print the matrix
print('\n\nMatrix C\n\n')
print(C)

# multiplication of Matrix A and Matrix B
print('\n\n Matrix Multilication of B and C: D = BxC\n\n')
D = B.dot(C)
print('\n\nMatrix D\n\n')
print(D)



Matrix B


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrix C


[[11 12 13]
 [14 15 16]
 [17 18 19]]


 Matrix Multilication of B and C: D = BxC




Matrix D


[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [13]:
#Inverse of a Matrix
print('/n/n Inverse of a Matrix/n/n')
print('\n\nMatrix A \n\n')
print(A)
#find the determinant
print('/n/n Determinant/n/n')
determinant = np.linalg.det(A)
print(determinant)

/n/n Inverse of a Matrix/n/n


Matrix A 


[[21 22 23]
 [24 25 26]
 [27 28 29]]
/n/n Determinant/n/n
-9.51619735392994e-16


In [14]:
#Find the inverse
print('\n\nMatrix A \n\n')
print(A)
inverse_A = np.linalg.inv(A)
print('\n\nInverse Matrix of A\n\n')
print(inverse_A)



Matrix A 


[[21 22 23]
 [24 25 26]
 [27 28 29]]


LinAlgError: Singular matrix